-- Chạy lại an toàn trong Supabase SQL Editor
-- Bảng nhân sự dùng cho trang /nhan-su

create table if not exists public.nhan_su (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

alter table public.nhan_su
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists nhan_su text,
  add column if not exists ma_nhan_su text,
  add column if not exists phong_ban text,
  add column if not exists chi_nhanh text,
  add column if not exists cong_viec text,
  add column if not exists vi_tri text,
  add column if not exists ca_lam text,
  add column if not exists trang_thai text default 'Đang làm',
  add column if not exists ten_dang_nhap text,
  add column if not exists mat_khau text,
  add column if not exists link_chu_ky text,
  add column if not exists quyen_xem jsonb not null default '[]'::jsonb,
  add column if not exists vi_tri_gan jsonb not null default '[]'::jsonb;

create index if not exists nhan_su_phong_ban_idx on public.nhan_su (phong_ban);
create index if not exists nhan_su_chi_nhanh_idx on public.nhan_su (chi_nhanh);
create index if not exists nhan_su_ten_idx on public.nhan_su (nhan_su);

alter table public.nhan_su enable row level security;

drop policy if exists "nhan_su_select_all" on public.nhan_su;
create policy "nhan_su_select_all"
  on public.nhan_su for select using (true);

drop policy if exists "nhan_su_insert_all" on public.nhan_su;
create policy "nhan_su_insert_all"
  on public.nhan_su for insert with check (true);

drop policy if exists "nhan_su_update_all" on public.nhan_su;
create policy "nhan_su_update_all"
  on public.nhan_su for update using (true) with check (true);

drop policy if exists "nhan_su_delete_all" on public.nhan_su;
create policy "nhan_su_delete_all"
  on public.nhan_su for delete using (true);

comment on table public.nhan_su is 'Danh sach nhan su theo phong ban va chi nhanh.';
comment on column public.nhan_su.nhan_su is 'Ho ten nhan su.';
comment on column public.nhan_su.ten_dang_nhap is 'Ten dang nhap he thong.';
comment on column public.nhan_su.mat_khau is 'Mat khau dang nhap.';
comment on column public.nhan_su.cong_viec is 'Chuc vu / cong viec — dung lam Vị trí khi tạo key phân quyền.';
comment on column public.nhan_su.vi_tri is 'Vi tri: dong bo tu cong_viec de khớp phân quyền (phong_ban + vi_tri).';
comment on column public.nhan_su.vi_tri_gan is
  'Danh sach vi tri duoc gan (nhieu): [{ department, position, permissionKey }].';
comment on column public.nhan_su.link_chu_ky is 'URL anh chu ky nhan su tren Cloudinary.';
