-- Tạo bảng chi tiết phân công nhân sự
create table if not exists public.phan_cong_nhan_su_chi_tiet (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  id_lenh_sx bigint not null,
  ma_lenh_sx text,
  vai_tro text,
  ma_nhan_su text not null,
  ngay_lam_viec date,
  thoi_gian_bat_dau time,
  thoi_gian_ket_thuc time,
  removable boolean default false,
  ghi_chu text
);

alter table public.phan_cong_nhan_su_chi_tiet enable row level security;

drop policy if exists "phan_cong_nhan_su_chi_tiet_select_all" on public.phan_cong_nhan_su_chi_tiet;
create policy "phan_cong_nhan_su_chi_tiet_select_all"
  on public.phan_cong_nhan_su_chi_tiet for select
  using (true);

drop policy if exists "phan_cong_nhan_su_chi_tiet_insert_all" on public.phan_cong_nhan_su_chi_tiet;
create policy "phan_cong_nhan_su_chi_tiet_insert_all"
  on public.phan_cong_nhan_su_chi_tiet for insert
  with check (true);

drop policy if exists "phan_cong_nhan_su_chi_tiet_update_all" on public.phan_cong_nhan_su_chi_tiet;
create policy "phan_cong_nhan_su_chi_tiet_update_all"
  on public.phan_cong_nhan_su_chi_tiet for update
  using (true)
  with check (true);

drop policy if exists "phan_cong_nhan_su_chi_tiet_delete_all" on public.phan_cong_nhan_su_chi_tiet;
create policy "phan_cong_nhan_su_chi_tiet_delete_all"
  on public.phan_cong_nhan_su_chi_tiet for delete
  using (true);

comment on table public.phan_cong_nhan_su_chi_tiet is 'Chi tiet phan cong nhan su cho lenh san xuat - denormalize de de query va tong hop.';
comment on column public.phan_cong_nhan_su_chi_tiet.id_lenh_sx is 'Foreign key reference to lenh_sx.id';
comment on column public.phan_cong_nhan_su_chi_tiet.ma_lenh_sx is 'Ma lenh san xuat (denormalize).';
comment on column public.phan_cong_nhan_su_chi_tiet.vai_tro is 'Vai tro: Truong ca, Nhan su chinh, Tho phu, Hoc viec.';
comment on column public.phan_cong_nhan_su_chi_tiet.ma_nhan_su is 'Ma nhan su duoc phan cong.';
comment on column public.phan_cong_nhan_su_chi_tiet.ngay_lam_viec is 'Ngay lam viec cua nhan su.';
comment on column public.phan_cong_nhan_su_chi_tiet.thoi_gian_bat_dau is 'Thoi gian bat dau ca lam.';
comment on column public.phan_cong_nhan_su_chi_tiet.thoi_gian_ket_thuc is 'Thoi gian ket thuc ca lam.';
comment on column public.phan_cong_nhan_su_chi_tiet.removable is 'Co the xoa duoc hay khong.';
comment on column public.phan_cong_nhan_su_chi_tiet.ghi_chu is 'Ghi chu them.';
