-- Bảng tổng hợp kết quả chốt kiểm kho — DB phiếu cân (njdlkyxdieefeebcyaov)
-- Chạy an toàn trong Supabase SQL Editor:
-- https://supabase.com/dashboard/project/njdlkyxdieefeebcyaov/sql/new
--
-- Mỗi dòng = 1 sản phẩm (theo mã NVL, không phân biệt hậu tố) đã gộp số lượng
-- khi chốt một đợt kiểm kho (xem bảng chi tiết public.kiem_kho).

create table if not exists public.kiem_kho_tong_hop (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  dot_kiem_kho text not null,
  ma_nvl text not null,
  ten_sp text,
  loai_sp text,
  tong_so_luong numeric not null default 0,
  chot_luc timestamptz not null default now(),
  nguoi_chot text
);

alter table public.kiem_kho_tong_hop
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists dot_kiem_kho text,
  add column if not exists ma_nvl text,
  add column if not exists ten_sp text,
  add column if not exists loai_sp text,
  add column if not exists tong_so_luong numeric not null default 0,
  add column if not exists chot_luc timestamptz not null default now(),
  add column if not exists nguoi_chot text;

create index if not exists kiem_kho_tong_hop_dot_idx on public.kiem_kho_tong_hop (dot_kiem_kho);
create index if not exists kiem_kho_tong_hop_ma_nvl_idx on public.kiem_kho_tong_hop (ma_nvl);
create unique index if not exists kiem_kho_tong_hop_dot_ma_nvl_uidx
  on public.kiem_kho_tong_hop (dot_kiem_kho, ma_nvl);

alter table public.kiem_kho_tong_hop enable row level security;

drop policy if exists "kiem_kho_tong_hop_select_all" on public.kiem_kho_tong_hop;
create policy "kiem_kho_tong_hop_select_all"
  on public.kiem_kho_tong_hop for select
  using (true);

drop policy if exists "kiem_kho_tong_hop_insert_all" on public.kiem_kho_tong_hop;
create policy "kiem_kho_tong_hop_insert_all"
  on public.kiem_kho_tong_hop for insert
  with check (true);

drop policy if exists "kiem_kho_tong_hop_update_all" on public.kiem_kho_tong_hop;
create policy "kiem_kho_tong_hop_update_all"
  on public.kiem_kho_tong_hop for update
  using (true)
  with check (true);

drop policy if exists "kiem_kho_tong_hop_delete_all" on public.kiem_kho_tong_hop;
create policy "kiem_kho_tong_hop_delete_all"
  on public.kiem_kho_tong_hop for delete
  using (true);

grant select, insert, update, delete on table public.kiem_kho_tong_hop to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

comment on table public.kiem_kho_tong_hop is 'Ket qua chot kiem cua tung dot — gop theo ma NVL (bo hau to), tong so luong.';
comment on column public.kiem_kho_tong_hop.dot_kiem_kho is 'Dot kiem kho — khop voi cot dot_kiem_kho cua bang public.kiem_kho.';
comment on column public.kiem_kho_tong_hop.ma_nvl is 'Ma NVL (tien to truoc dau _), khong phan biet hau to.';
comment on column public.kiem_kho_tong_hop.ten_sp is 'Ten san pham.';
comment on column public.kiem_kho_tong_hop.loai_sp is 'Loai san pham.';
comment on column public.kiem_kho_tong_hop.tong_so_luong is 'Tong so dong da quet cua ma NVL nay trong dot.';
comment on column public.kiem_kho_tong_hop.chot_luc is 'Thoi diem chot dot.';
comment on column public.kiem_kho_tong_hop.nguoi_chot is 'Nguoi thuc hien chot dot.';
