-- Chay lai an toan trong Supabase SQL Editor

create table if not exists public.danh_sach_may (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

-- Bang da ton tai tu truoc (khong co cot id) -> them id
do $$
begin
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'danh_sach_may'
      and column_name = 'id'
  ) then
    alter table public.danh_sach_may
      add column id bigint generated by default as identity;
  end if;
end $$;

alter table public.danh_sach_may
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists ma_may text,
  add column if not exists ten_may text,
  add column if not exists loai_may text,
  add column if not exists chi_nhanh text,
  add column if not exists vi_tri text,
  add column if not exists trang_thai text default 'Đang dùng',
  add column if not exists ghi_chu text,
  add column if not exists anh_url text,
  add column if not exists anh_public_id text,
  add column if not exists dinh_luong numeric(10,2),
  add column if not exists ty_le_tron jsonb not null default '[]'::jsonb;

alter table public.danh_sach_may enable row level security;

drop policy if exists "danh_sach_may_select_all" on public.danh_sach_may;
create policy "danh_sach_may_select_all"
  on public.danh_sach_may for select
  using (true);

drop policy if exists "danh_sach_may_insert_all" on public.danh_sach_may;
create policy "danh_sach_may_insert_all"
  on public.danh_sach_may for insert
  with check (true);

drop policy if exists "danh_sach_may_update_all" on public.danh_sach_may;
create policy "danh_sach_may_update_all"
  on public.danh_sach_may for update
  using (true)
  with check (true);

drop policy if exists "danh_sach_may_delete_all" on public.danh_sach_may;
create policy "danh_sach_may_delete_all"
  on public.danh_sach_may for delete
  using (true);

comment on table public.danh_sach_may is 'Danh sach may san xuat.';
comment on column public.danh_sach_may.id is 'ID may (khoa chinh).';
comment on column public.danh_sach_may.ma_may is 'Ma may.';
comment on column public.danh_sach_may.ten_may is 'Ten may.';
comment on column public.danh_sach_may.anh_url is 'URL hinh anh may.';
comment on column public.danh_sach_may.anh_public_id is 'Cloudinary public id cua hinh anh may.';
comment on column public.danh_sach_may.dinh_luong is 'Dinh luong may, 2 chu so thap phan.';
comment on column public.danh_sach_may.ty_le_tron is 'Ty le tron NVL dang JSONB: [{ma_nvl, ten_nvl, phan_tram}].';
