-- Chạy lại an toàn trong Supabase SQL Editor.
-- Danh mục xe và bảng đối chiếu lương/chuyến đi của tài xế.

create table if not exists public.danh_sach_xe (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

alter table public.danh_sach_xe
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists loai_xe text,
  add column if not exists bien_so_xe text,
  add column if not exists ma_tai_xe text,
  add column if not exists tai_xe_phu_trach text,
  add column if not exists trang_thai text not null default 'Đang sử dụng',
  add column if not exists ghi_chu text;

create unique index if not exists danh_sach_xe_bien_so_unique_idx
  on public.danh_sach_xe (upper(bien_so_xe));
create index if not exists danh_sach_xe_tai_xe_idx
  on public.danh_sach_xe (ma_tai_xe, tai_xe_phu_trach);

alter table public.danh_sach_xe enable row level security;

drop policy if exists "danh_sach_xe_select_all" on public.danh_sach_xe;
create policy "danh_sach_xe_select_all" on public.danh_sach_xe for select using (true);
drop policy if exists "danh_sach_xe_insert_all" on public.danh_sach_xe;
create policy "danh_sach_xe_insert_all" on public.danh_sach_xe for insert with check (true);
drop policy if exists "danh_sach_xe_update_all" on public.danh_sach_xe;
create policy "danh_sach_xe_update_all" on public.danh_sach_xe for update using (true) with check (true);
drop policy if exists "danh_sach_xe_delete_all" on public.danh_sach_xe;
create policy "danh_sach_xe_delete_all" on public.danh_sach_xe for delete using (true);

create table if not exists public.doi_chieu_lai_xe (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

alter table public.doi_chieu_lai_xe
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists nam integer,
  add column if not exists thang integer,
  add column if not exists ma_nhan_su text,
  add column if not exists ten_tai_xe text,
  add column if not exists xe_id bigint,
  add column if not exists loai_xe_di text,
  add column if not exists bien_so_xe text,
  add column if not exists tong_cong_quy_doi numeric(14,2) not null default 0,
  add column if not exists so_chuyen_di numeric(14,2) not null default 0,
  add column if not exists tong_km_thuc_te numeric(14,2) not null default 0,
  add column if not exists tien_thuong_luat numeric(16,2) not null default 0,
  add column if not exists tien_thuong_chuyen numeric(16,2) not null default 0,
  add column if not exists thuong_doanh_so numeric(16,2) not null default 0,
  add column if not exists doanh_so numeric(18,2) not null default 0,
  add column if not exists ghi_chu text;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'doi_chieu_lai_xe_thang_check'
  ) then
    alter table public.doi_chieu_lai_xe
      add constraint doi_chieu_lai_xe_thang_check check (thang between 1 and 12);
  end if;
end $$;

create index if not exists doi_chieu_lai_xe_ky_idx
  on public.doi_chieu_lai_xe (nam desc, thang desc);
create index if not exists doi_chieu_lai_xe_tai_xe_idx
  on public.doi_chieu_lai_xe (ma_nhan_su, ten_tai_xe);

alter table public.doi_chieu_lai_xe enable row level security;

drop policy if exists "doi_chieu_lai_xe_select_all" on public.doi_chieu_lai_xe;
create policy "doi_chieu_lai_xe_select_all" on public.doi_chieu_lai_xe for select using (true);
drop policy if exists "doi_chieu_lai_xe_insert_all" on public.doi_chieu_lai_xe;
create policy "doi_chieu_lai_xe_insert_all" on public.doi_chieu_lai_xe for insert with check (true);
drop policy if exists "doi_chieu_lai_xe_update_all" on public.doi_chieu_lai_xe;
create policy "doi_chieu_lai_xe_update_all" on public.doi_chieu_lai_xe for update using (true) with check (true);
drop policy if exists "doi_chieu_lai_xe_delete_all" on public.doi_chieu_lai_xe;
create policy "doi_chieu_lai_xe_delete_all" on public.doi_chieu_lai_xe for delete using (true);

comment on table public.danh_sach_xe is 'Danh muc xe va tai xe phu trach.';
comment on table public.doi_chieu_lai_xe is 'Doi chieu cong, chuyen, km va thuong cua lai xe theo thang.';

create table if not exists public.chi_phi_xe (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

alter table public.chi_phi_xe
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists ngay_gio timestamptz not null default now(),
  add column if not exists loai_chi_phi text not null default 'CHI PHÍ XĂNG DẦU',
  add column if not exists ten_chi_phi text,
  add column if not exists so_tien numeric(18,2) not null default 0,
  add column if not exists xe_id bigint,
  add column if not exists bien_so_xe text,
  add column if not exists ma_nhan_su text,
  add column if not exists nhan_vien_phu_trach text,
  add column if not exists hoa_don_url text,
  add column if not exists hoa_don_public_id text,
  add column if not exists ghi_chu text;

create index if not exists chi_phi_xe_ngay_gio_idx
  on public.chi_phi_xe (ngay_gio desc);
create index if not exists chi_phi_xe_bien_so_idx
  on public.chi_phi_xe (bien_so_xe);

alter table public.chi_phi_xe enable row level security;

drop policy if exists "chi_phi_xe_select_all" on public.chi_phi_xe;
create policy "chi_phi_xe_select_all" on public.chi_phi_xe for select using (true);
drop policy if exists "chi_phi_xe_insert_all" on public.chi_phi_xe;
create policy "chi_phi_xe_insert_all" on public.chi_phi_xe for insert with check (true);
drop policy if exists "chi_phi_xe_update_all" on public.chi_phi_xe;
create policy "chi_phi_xe_update_all" on public.chi_phi_xe for update using (true) with check (true);
drop policy if exists "chi_phi_xe_delete_all" on public.chi_phi_xe;
create policy "chi_phi_xe_delete_all" on public.chi_phi_xe for delete using (true);

create table if not exists public.nhat_ky_xe (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

alter table public.nhat_ky_xe
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists ngay_gio timestamptz not null default now(),
  add column if not exists ca text,
  add column if not exists xe_id bigint,
  add column if not exists bien_so_xe text,
  add column if not exists ma_nhan_su text,
  add column if not exists nhan_vien_phu_trach text,
  add column if not exists tong_mat_hang numeric(14,2) not null default 0,
  add column if not exists tong_doanh_thu numeric(18,2) not null default 0,
  add column if not exists tong_chi_phi numeric(18,2) not null default 0,
  add column if not exists chi_tiet_mat_hang jsonb not null default '[]'::jsonb,
  add column if not exists ten_mat_hang text,
  add column if not exists ma_san_pham text,
  add column if not exists sl_cuon_cach_nhiet numeric(14,2) not null default 0,
  add column if not exists doanh_thu_cach_nhiet numeric(18,2) not null default 0,
  add column if not exists so_luong_bao_bi numeric(14,2) not null default 0,
  add column if not exists doanh_thu_bao_bi numeric(18,2) not null default 0,
  add column if not exists so_luong_tui_tam_gia_cong numeric(14,2) not null default 0,
  add column if not exists doanh_thu_tui_tam_gia_cong numeric(18,2) not null default 0,
  add column if not exists so_luong_tui_niem_phong numeric(14,2) not null default 0,
  add column if not exists doanh_thu_tui_niem_phong numeric(18,2) not null default 0,
  add column if not exists so_luong_tui_cao_cap_chong_soc numeric(14,2) not null default 0,
  add column if not exists thanh_tien_tui_cao_cap_chong_soc numeric(18,2) not null default 0,
  add column if not exists ds_poly numeric(18,2) not null default 0,
  add column if not exists thuong_chuyen_giao_hang numeric(16,2) not null default 0,
  add column if not exists cong_lai_xe_theo_km numeric(14,2) not null default 0,
  add column if not exists thuong_km_di numeric(16,2) not null default 0,
  add column if not exists chi_so_km_truoc numeric(14,2) not null default 0,
  add column if not exists chi_so_km_ve numeric(14,2) not null default 0,
  add column if not exists so_km_thuc_te numeric(14,2) not null default 0,
  add column if not exists so_lenh numeric(14,2) not null default 0,
  add column if not exists so_chuyen numeric(14,2) not null default 0,
  add column if not exists ten_lx1 text,
  add column if not exists cong_lx1 numeric(14,2) not null default 0,
  add column if not exists luong_lx1 numeric(16,2) not null default 0,
  add column if not exists tien_an_lx1 numeric(16,2) not null default 0,
  add column if not exists tien_ds_lx1 numeric(16,2) not null default 0,
  add column if not exists tien_thuong_chuyen_lx1 numeric(16,2) not null default 0,
  add column if not exists tien_luat_lx1 numeric(16,2) not null default 0,
  add column if not exists ghi_chu text;

create index if not exists nhat_ky_xe_ngay_gio_idx
  on public.nhat_ky_xe (ngay_gio desc);
create index if not exists nhat_ky_xe_bien_so_idx
  on public.nhat_ky_xe (bien_so_xe);

alter table public.nhat_ky_xe enable row level security;

drop policy if exists "nhat_ky_xe_select_all" on public.nhat_ky_xe;
create policy "nhat_ky_xe_select_all" on public.nhat_ky_xe for select using (true);
drop policy if exists "nhat_ky_xe_insert_all" on public.nhat_ky_xe;
create policy "nhat_ky_xe_insert_all" on public.nhat_ky_xe for insert with check (true);
drop policy if exists "nhat_ky_xe_update_all" on public.nhat_ky_xe;
create policy "nhat_ky_xe_update_all" on public.nhat_ky_xe for update using (true) with check (true);
drop policy if exists "nhat_ky_xe_delete_all" on public.nhat_ky_xe;
create policy "nhat_ky_xe_delete_all" on public.nhat_ky_xe for delete using (true);

comment on table public.chi_phi_xe is 'Chi phi van hanh xe, hoa don va nhan vien phu trach.';
comment on table public.nhat_ky_xe is 'Nhat ky doanh thu, chi phi va mat hang theo xe va ca.';

create table if not exists public.yeu_cau_xuat_hang_xe (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  so_yeu_cau text not null,
  ngay_yeu_cau date not null default current_date,
  dia_diem_giao text not null,
  hang_hoa text not null,
  so_luong numeric(14,2) not null default 0,
  don_vi text,
  xe_id bigint,
  bien_so_xe text,
  ma_nhan_su text,
  ten_tai_xe text,
  trang_thai text not null default 'Chờ xuất hàng',
  ghi_chu text
);

create index if not exists yeu_cau_xuat_hang_xe_ngay_idx
  on public.yeu_cau_xuat_hang_xe (ngay_yeu_cau desc);
create index if not exists yeu_cau_xuat_hang_xe_bsx_idx
  on public.yeu_cau_xuat_hang_xe (bien_so_xe);

alter table public.yeu_cau_xuat_hang_xe enable row level security;
drop policy if exists "yeu_cau_xuat_hang_xe_select_all" on public.yeu_cau_xuat_hang_xe;
create policy "yeu_cau_xuat_hang_xe_select_all" on public.yeu_cau_xuat_hang_xe for select using (true);
drop policy if exists "yeu_cau_xuat_hang_xe_insert_all" on public.yeu_cau_xuat_hang_xe;
create policy "yeu_cau_xuat_hang_xe_insert_all" on public.yeu_cau_xuat_hang_xe for insert with check (true);
drop policy if exists "yeu_cau_xuat_hang_xe_update_all" on public.yeu_cau_xuat_hang_xe;
create policy "yeu_cau_xuat_hang_xe_update_all" on public.yeu_cau_xuat_hang_xe for update using (true) with check (true);
drop policy if exists "yeu_cau_xuat_hang_xe_delete_all" on public.yeu_cau_xuat_hang_xe;
create policy "yeu_cau_xuat_hang_xe_delete_all" on public.yeu_cau_xuat_hang_xe for delete using (true);
