-- Bảng quy đổi sản phẩm. Chạy trong Supabase SQL Editor của DB chính.
create table if not exists public.san_pham_quy_doi (
  id bigint generated by default as identity primary key,
  san_pham_id uuid not null references public.san_pham(id) on update cascade on delete restrict,
  kho_tam_rong_m numeric,
  kho_tam_dai_m numeric,
  kho_cuon_rong_m numeric,
  kho_cuon_dai_m numeric,
  dien_tich_m2 numeric,
  trong_luong_kg_m_dai numeric,
  trong_luong_kg_m2 numeric,
  trong_luong_kg_tam numeric,
  trong_luong_kg_cuon numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint san_pham_quy_doi_so_duong_check check (
    (kho_tam_rong_m is null or kho_tam_rong_m > 0)
    and (kho_tam_dai_m is null or kho_tam_dai_m > 0)
    and (kho_cuon_rong_m is null or kho_cuon_rong_m > 0)
    and (kho_cuon_dai_m is null or kho_cuon_dai_m > 0)
    and (dien_tich_m2 is null or dien_tich_m2 > 0)
    and (trong_luong_kg_m_dai is null or trong_luong_kg_m_dai > 0)
    and (trong_luong_kg_m2 is null or trong_luong_kg_m2 > 0)
    and (trong_luong_kg_tam is null or trong_luong_kg_tam > 0)
    and (trong_luong_kg_cuon is null or trong_luong_kg_cuon > 0)
  )
);
create index if not exists san_pham_quy_doi_san_pham_id_idx on public.san_pham_quy_doi (san_pham_id);
create unique index if not exists san_pham_quy_doi_san_pham_key
  on public.san_pham_quy_doi (san_pham_id);
alter table public.san_pham_quy_doi enable row level security;
drop policy if exists "san_pham_quy_doi_select_all" on public.san_pham_quy_doi;
create policy "san_pham_quy_doi_select_all" on public.san_pham_quy_doi for select using (true);
drop policy if exists "san_pham_quy_doi_insert_all" on public.san_pham_quy_doi;
create policy "san_pham_quy_doi_insert_all" on public.san_pham_quy_doi for insert with check (true);
drop policy if exists "san_pham_quy_doi_update_all" on public.san_pham_quy_doi;
create policy "san_pham_quy_doi_update_all" on public.san_pham_quy_doi for update using (true) with check (true);
drop policy if exists "san_pham_quy_doi_delete_all" on public.san_pham_quy_doi;
create policy "san_pham_quy_doi_delete_all" on public.san_pham_quy_doi for delete using (true);
