-- Lệnh xuất hàng cho khách hàng (Kinh doanh)
create table if not exists public.lenh_xuat_hang (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  ma_lenh text not null,
  ngay_xuat date not null default current_date,
  ma_khach_hang text,
  ten_khach_hang text not null,
  dia_chi_giao text,
  so_dien_thoai text,
  nhan_vien text,
  trang_thai text not null default 'Chờ xuất',
  ghi_chu text,
  chi_tiet jsonb not null default '[]'::jsonb
);

create unique index if not exists lenh_xuat_hang_ma_lenh_uidx
  on public.lenh_xuat_hang (ma_lenh);

create index if not exists lenh_xuat_hang_ngay_idx
  on public.lenh_xuat_hang (ngay_xuat desc);

create index if not exists lenh_xuat_hang_khach_idx
  on public.lenh_xuat_hang (ten_khach_hang);

alter table public.lenh_xuat_hang enable row level security;

drop policy if exists "lenh_xuat_hang_select_all" on public.lenh_xuat_hang;
create policy "lenh_xuat_hang_select_all" on public.lenh_xuat_hang for select using (true);

drop policy if exists "lenh_xuat_hang_insert_all" on public.lenh_xuat_hang;
create policy "lenh_xuat_hang_insert_all" on public.lenh_xuat_hang for insert with check (true);

drop policy if exists "lenh_xuat_hang_update_all" on public.lenh_xuat_hang;
create policy "lenh_xuat_hang_update_all" on public.lenh_xuat_hang for update using (true) with check (true);

drop policy if exists "lenh_xuat_hang_delete_all" on public.lenh_xuat_hang;
create policy "lenh_xuat_hang_delete_all" on public.lenh_xuat_hang for delete using (true);
