create table if not exists public.phieu_can_dinh_ki (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

alter table public.phieu_can_dinh_ki
  add column if not exists document_no text,
  add column if not exists report_date date,
  add column if not exists ngay_san_xuat date,
  add column if not exists ca_san_xuat text,
  add column if not exists ten_cn_1 text,
  add column if not exists ten_cn_2 text,
  add column if not exists ten_nguoi_can text,
  add column if not exists ma_san_pham text,
  add column if not exists ten_san_pham text,
  add column if not exists ten_may_san_xuat text,
  add column if not exists lan_can integer,
  add column if not exists gio_can time,
  add column if not exists trong_luong_loi text,
  add column if not exists anh_trong_luong_loi_url text,
  add column if not exists anh_trong_luong_loi_public_id text,
  add column if not exists trong_luong_bi text,
  add column if not exists trong_luong text,
  add column if not exists tong_trong_luong numeric generated always as (
    (
      case
        when replace(trim(coalesce(trong_luong_loi, '')), ',', '.') ~ '^-?[0-9]+(\.[0-9]+)?$'
          then replace(trim(trong_luong_loi), ',', '.')::numeric
        else 0
      end
    ) +
    (
      case
        when replace(trim(coalesce(trong_luong_bi, '')), ',', '.') ~ '^-?[0-9]+(\.[0-9]+)?$'
          then replace(trim(trong_luong_bi), ',', '.')::numeric
        else 0
      end
    ) +
    (
      case
        when replace(trim(coalesce(trong_luong, '')), ',', '.') ~ '^-?[0-9]+(\.[0-9]+)?$'
          then replace(trim(trong_luong), ',', '.')::numeric
        else 0
      end
    )
  ) stored,
  add column if not exists anh_url text,
  add column if not exists anh_public_id text,
  add column if not exists nghiem_thu text,
  add column if not exists ghi_chu text;

alter table public.phieu_can_dinh_ki enable row level security;

drop policy if exists "phieu_can_dinh_ki_select_all" on public.phieu_can_dinh_ki;
create policy "phieu_can_dinh_ki_select_all"
  on public.phieu_can_dinh_ki for select
  using (true);

drop policy if exists "phieu_can_dinh_ki_insert_all" on public.phieu_can_dinh_ki;
create policy "phieu_can_dinh_ki_insert_all"
  on public.phieu_can_dinh_ki for insert
  with check (true);

drop policy if exists "phieu_can_dinh_ki_update_all" on public.phieu_can_dinh_ki;
create policy "phieu_can_dinh_ki_update_all"
  on public.phieu_can_dinh_ki for update
  using (true)
  with check (true);

drop policy if exists "phieu_can_dinh_ki_delete_all" on public.phieu_can_dinh_ki;
create policy "phieu_can_dinh_ki_delete_all"
  on public.phieu_can_dinh_ki for delete
  using (true);

comment on column public.phieu_can_dinh_ki.lan_can is 'Lan can tu dong tang trong cung mot phieu.';
comment on column public.phieu_can_dinh_ki.gio_can is 'Gio can tu dong lay tai thoi diem them dong, dinh dang time.';
comment on column public.phieu_can_dinh_ki.ten_cn_2 is 'Ten cong nhan 2.';
comment on column public.phieu_can_dinh_ki.ten_nguoi_can is 'Nguoi can / nguoi nhap lieu.';
comment on column public.phieu_can_dinh_ki.ma_san_pham is 'Ma san pham (ma_sp) quet QR hoac nhap tay.';
comment on column public.phieu_can_dinh_ki.ten_san_pham is 'Ten san pham lay tu san_pham.ten_sp.';
comment on column public.phieu_can_dinh_ki.ten_may_san_xuat is 'Ten may san xuat nhap tay.';
comment on column public.phieu_can_dinh_ki.trong_luong_loi is 'Trong luong loi.';
comment on column public.phieu_can_dinh_ki.trong_luong_bi is 'Trong luong bi (kg).';
comment on column public.phieu_can_dinh_ki.tong_trong_luong is 'Tong trong luong = trong_luong_loi + trong_luong_bi + trong_luong.';
comment on column public.phieu_can_dinh_ki.anh_trong_luong_loi_url is 'Cloudinary secure URL cua anh trong luong loi.';
comment on column public.phieu_can_dinh_ki.anh_url is 'Cloudinary secure URL cua anh can.';
comment on column public.phieu_can_dinh_ki.nghiem_thu is 'Ket qua nghiem thu: Dat hoac Khong dat.';
comment on column public.phieu_can_dinh_ki.ghi_chu is 'Ghi chu tung lan can.';
