create table if not exists public.danh_sach_may (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

alter table public.danh_sach_may
  add column if not exists ma_may text,
  add column if not exists ten_may text,
  add column if not exists loai_may text,
  add column if not exists chi_nhanh text,
  add column if not exists vi_tri text,
  add column if not exists trang_thai text default 'Đang dùng',
  add column if not exists ghi_chu text;

alter table public.danh_sach_may enable row level security;

drop policy if exists "danh_sach_may_select_all" on public.danh_sach_may;
create policy "danh_sach_may_select_all"
  on public.danh_sach_may for select
  using (true);

drop policy if exists "danh_sach_may_insert_all" on public.danh_sach_may;
create policy "danh_sach_may_insert_all"
  on public.danh_sach_may for insert
  with check (true);

drop policy if exists "danh_sach_may_update_all" on public.danh_sach_may;
create policy "danh_sach_may_update_all"
  on public.danh_sach_may for update
  using (true)
  with check (true);

drop policy if exists "danh_sach_may_delete_all" on public.danh_sach_may;
create policy "danh_sach_may_delete_all"
  on public.danh_sach_may for delete
  using (true);

comment on table public.danh_sach_may is 'Danh sach may san xuat.';
comment on column public.danh_sach_may.ma_may is 'Ma may.';
comment on column public.danh_sach_may.ten_may is 'Ten may.';
