-- Chạy trong Supabase SQL Editor.
create table if not exists public.ton_kho_toi_thieu_toi_da (
  id bigint generated by default as identity primary key,
  san_pham_id text not null,
  quy_cach text not null default '',
  don_vi text not null check (don_vi in ('Tấm', 'Cuộn')),
  ton_kho_toi_thieu integer not null check (ton_kho_toi_thieu >= 0),
  ton_kho_toi_da integer not null check (ton_kho_toi_da >= ton_kho_toi_thieu),
  thang smallint not null check (thang between 1 and 12),
  nam smallint not null check (nam between 2000 and 2100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (san_pham_id, thang, nam)
);

create index if not exists ton_kho_toi_thieu_toi_da_thang_nam_idx
  on public.ton_kho_toi_thieu_toi_da (nam desc, thang desc);
