-- Chay trong Supabase SQL Editor (an toan khi chay lai)

create table if not exists public.lenh_sx (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

alter table public.lenh_sx
  add column if not exists ma_lenh_sx text,
  add column if not exists ten_lenh_sx text,
  add column if not exists ma_hang text,
  add column if not exists ten_hang text,
  add column if not exists so_luong numeric,
  add column if not exists don_vi text,
  add column if not exists trang_thai text default 'Chờ sx',
  add column if not exists khach_hang text,
  add column if not exists ma_don_hang text,
  add column if not exists ngay_bat_dau date,
  add column if not exists ngay_ket_thuc date,
  add column if not exists ngay_gio_bat_dau timestamptz,
  add column if not exists ngay_gio_ket_thuc timestamptz,
  add column if not exists ca text,
  add column if not exists nhan_su text,
  add column if not exists truong_ca text,
  add column if not exists nhan_su_chinh text,
  add column if not exists tho_phu text,
  add column if not exists hoc_viec text,
  add column if not exists may text,
  add column if not exists ghi_chu text,
  add column if not exists cong_nhan text,
  add column if not exists nguoi_tao text,
  add column if not exists san_pham text,
  add column if not exists vi_tri text,
  add column if not exists thu_tu_uu_tien integer default 0;

alter table public.don_hang
  add column if not exists lenh_sx text;

alter table public.lenh_sx enable row level security;

drop policy if exists "lenh_sx_select_all" on public.lenh_sx;
create policy "lenh_sx_select_all"
  on public.lenh_sx for select
  using (true);

drop policy if exists "lenh_sx_insert_all" on public.lenh_sx;
create policy "lenh_sx_insert_all"
  on public.lenh_sx for insert
  with check (true);

drop policy if exists "lenh_sx_update_all" on public.lenh_sx;
create policy "lenh_sx_update_all"
  on public.lenh_sx for update
  using (true)
  with check (true);

drop policy if exists "lenh_sx_delete_all" on public.lenh_sx;
create policy "lenh_sx_delete_all"
  on public.lenh_sx for delete
  using (true);

comment on table public.lenh_sx is 'Lenh san xuat.';
comment on column public.lenh_sx.ma_lenh_sx is 'Ma lenh san xuat.';
comment on column public.lenh_sx.trang_thai is 'Trang thai: Cho sx, Dang sx, Hoan thanh, Huy.';
comment on column public.lenh_sx.truong_ca is 'Truong ca phu trach lenh san xuat.';
comment on column public.lenh_sx.nhan_su_chinh is 'Nhan su chinh thuc hien lenh san xuat.';
comment on column public.lenh_sx.tho_phu is 'Tho phu cua lenh san xuat.';
comment on column public.lenh_sx.hoc_viec is 'Nhan su hoc viec cua lenh san xuat.';
