create table if not exists public.bao_cao_hang_hong (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

alter table public.bao_cao_hang_hong
  add column if not exists document_no text,
  add column if not exists report_date date,
  add column if not exists ngay_san_xuat date,
  add column if not exists ca_san_xuat text,
  add column if not exists ten_cn_1 text,
  add column if not exists ten_cn_2 text,
  add column if not exists ten_nguoi_can text,
  add column if not exists ma_san_pham text,
  add column if not exists ten_san_pham text,
  add column if not exists ten_may_san_xuat text,
  add column if not exists lan_can integer,
  add column if not exists gio_can time,
  add column if not exists trong_luong_loi text,
  add column if not exists anh_trong_luong_loi_url text,
  add column if not exists anh_trong_luong_loi_public_id text,
  add column if not exists trong_luong text,
  add column if not exists anh_url text,
  add column if not exists anh_public_id text;

alter table public.bao_cao_hang_hong enable row level security;

drop policy if exists "bao_cao_hang_hong_select_all" on public.bao_cao_hang_hong;
create policy "bao_cao_hang_hong_select_all"
  on public.bao_cao_hang_hong for select
  using (true);

drop policy if exists "bao_cao_hang_hong_insert_all" on public.bao_cao_hang_hong;
create policy "bao_cao_hang_hong_insert_all"
  on public.bao_cao_hang_hong for insert
  with check (true);

drop policy if exists "bao_cao_hang_hong_update_all" on public.bao_cao_hang_hong;
create policy "bao_cao_hang_hong_update_all"
  on public.bao_cao_hang_hong for update
  using (true)
  with check (true);

drop policy if exists "bao_cao_hang_hong_delete_all" on public.bao_cao_hang_hong;
create policy "bao_cao_hang_hong_delete_all"
  on public.bao_cao_hang_hong for delete
  using (true);

comment on column public.bao_cao_hang_hong.lan_can is 'Lan can tu dong tang trong cung mot phieu.';
comment on column public.bao_cao_hang_hong.gio_can is 'Gio can tu dong lay tai thoi diem them dong, dinh dang time.';
comment on column public.bao_cao_hang_hong.ten_cn_2 is 'Ten cong nhan 2.';
comment on column public.bao_cao_hang_hong.ten_nguoi_can is 'Nguoi can / nguoi nhap lieu.';
comment on column public.bao_cao_hang_hong.ma_san_pham is 'Ma san pham (ma_sp) quet QR hoac nhap tay.';
comment on column public.bao_cao_hang_hong.ten_san_pham is 'Ten san pham lay tu san_pham.ten_sp.';
comment on column public.bao_cao_hang_hong.ten_may_san_xuat is 'Ten may san xuat nhap tay.';
comment on column public.bao_cao_hang_hong.trong_luong_loi is 'Trong luong loi.';
comment on column public.bao_cao_hang_hong.anh_trong_luong_loi_url is 'Cloudinary secure URL cua anh trong luong loi.';
comment on column public.bao_cao_hang_hong.anh_url is 'Cloudinary secure URL cua anh can.';
