-- Quản lý kho — DB chính hệ thống (frgoljnscvpxbctplmiq / he-thong)
-- https://supabase.com/dashboard/project/frgoljnscvpxbctplmiq/sql/new

create table if not exists public.quan_ly_kho (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  ten_kho text,
  vi_tri text,
  ten_vi_tri text,
  nguoi_phu_trach text
);

alter table public.quan_ly_kho
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists ten_kho text,
  add column if not exists vi_tri text,
  add column if not exists ten_vi_tri text,
  add column if not exists nguoi_phu_trach text;

create index if not exists quan_ly_kho_ten_kho_idx on public.quan_ly_kho (ten_kho);

alter table public.quan_ly_kho enable row level security;

drop policy if exists "quan_ly_kho_select_all" on public.quan_ly_kho;
create policy "quan_ly_kho_select_all"
  on public.quan_ly_kho for select
  using (true);

drop policy if exists "quan_ly_kho_insert_all" on public.quan_ly_kho;
create policy "quan_ly_kho_insert_all"
  on public.quan_ly_kho for insert
  with check (true);

drop policy if exists "quan_ly_kho_update_all" on public.quan_ly_kho;
create policy "quan_ly_kho_update_all"
  on public.quan_ly_kho for update
  using (true)
  with check (true);

drop policy if exists "quan_ly_kho_delete_all" on public.quan_ly_kho;
create policy "quan_ly_kho_delete_all"
  on public.quan_ly_kho for delete
  using (true);

grant select, insert, update, delete on table public.quan_ly_kho to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

comment on table public.quan_ly_kho is 'Danh muc quan ly kho.';
comment on column public.quan_ly_kho.ten_kho is 'Ten kho.';
comment on column public.quan_ly_kho.vi_tri is 'Ma / ky hieu vi tri.';
comment on column public.quan_ly_kho.ten_vi_tri is 'Ten vi tri.';
comment on column public.quan_ly_kho.nguoi_phu_trach is 'Nguoi phu trach kho.';
