-- Bảng ghi lại các lần đã xử lý (tạo phiếu điều chỉnh) cho một dòng chênh lệch
-- kiểm kê — DB "kiem-kho" (project grlcgkzotqishzxwpddc), cùng chỗ với
-- public.kiem_kho_tong_hop.
-- Chạy an toàn trong Supabase SQL Editor:
-- https://supabase.com/dashboard/project/grlcgkzotqishzxwpddc/sql/new
--
-- Mỗi dòng = 1 lần tạo phiếu nhập/xuất điều chỉnh tồn kho cho 1 mã sản phẩm
-- nguyên bản, giữ đầy đủ hậu tố lô/serial sau dấu _ nếu có.
-- của 1 đợt kiểm kho, sau khi đối chiếu số kiểm kê (kiem_kho_tong_hop) với
-- tồn cuối kỳ sổ sách của thành phẩm (RPC ton_kho_san_pham_gop ở DB chính).
-- Dùng để màn "Xử lý chênh lệch" biết dòng nào đã xử lý mà không phải tính lại.

create table if not exists public.kiem_kho_chenh_lech_xu_ly (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  dot_kiem_kho text not null,
  ma_sp text not null,
  loai_phieu text,
  so_luong_dieu_chinh numeric,
  ma_phieu_dieu_chinh text,
  ghi_chu text,
  nguoi_xu_ly text,
  xu_ly_luc timestamptz not null default now()
);

-- Nếu môi trường cũ đã từng tạo cột ma_nvl, đổi tên cột đó sang ma_sp.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'kiem_kho_chenh_lech_xu_ly'
      and column_name = 'ma_nvl'
  ) and not exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'kiem_kho_chenh_lech_xu_ly'
      and column_name = 'ma_sp'
  ) then
    alter table public.kiem_kho_chenh_lech_xu_ly rename column ma_nvl to ma_sp;
  end if;
end $$;

alter table public.kiem_kho_chenh_lech_xu_ly
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists dot_kiem_kho text,
  add column if not exists ma_sp text,
  add column if not exists loai_phieu text,
  add column if not exists so_luong_dieu_chinh numeric,
  add column if not exists ma_phieu_dieu_chinh text,
  add column if not exists ghi_chu text,
  add column if not exists nguoi_xu_ly text,
  add column if not exists xu_ly_luc timestamptz not null default now();

-- Trường này từng dùng để phân biệt NVL/thành phẩm. Luồng hiện tại chỉ xử lý
-- sản phẩm nên không cần lưu một giá trị cố định nữa.
alter table public.kiem_kho_chenh_lech_xu_ly
  drop column if exists loai_kho;

create index if not exists kiem_kho_chenh_lech_xu_ly_dot_idx
  on public.kiem_kho_chenh_lech_xu_ly (dot_kiem_kho);
drop index if exists public.kiem_kho_chenh_lech_xu_ly_dot_ma_nvl_idx;
create index if not exists kiem_kho_chenh_lech_xu_ly_dot_ma_sp_idx
  on public.kiem_kho_chenh_lech_xu_ly (dot_kiem_kho, ma_sp);

alter table public.kiem_kho_chenh_lech_xu_ly enable row level security;

drop policy if exists "kiem_kho_chenh_lech_xu_ly_select_all" on public.kiem_kho_chenh_lech_xu_ly;
create policy "kiem_kho_chenh_lech_xu_ly_select_all"
  on public.kiem_kho_chenh_lech_xu_ly for select
  using (true);

drop policy if exists "kiem_kho_chenh_lech_xu_ly_insert_all" on public.kiem_kho_chenh_lech_xu_ly;
create policy "kiem_kho_chenh_lech_xu_ly_insert_all"
  on public.kiem_kho_chenh_lech_xu_ly for insert
  with check (true);

drop policy if exists "kiem_kho_chenh_lech_xu_ly_update_all" on public.kiem_kho_chenh_lech_xu_ly;
create policy "kiem_kho_chenh_lech_xu_ly_update_all"
  on public.kiem_kho_chenh_lech_xu_ly for update
  using (true)
  with check (true);

drop policy if exists "kiem_kho_chenh_lech_xu_ly_delete_all" on public.kiem_kho_chenh_lech_xu_ly;
create policy "kiem_kho_chenh_lech_xu_ly_delete_all"
  on public.kiem_kho_chenh_lech_xu_ly for delete
  using (true);

grant select, insert, update, delete on table public.kiem_kho_chenh_lech_xu_ly to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

comment on table public.kiem_kho_chenh_lech_xu_ly is
  'Lich su tao phieu dieu chinh ton kho cho tung dong chenh lech kiem ke (man Xu ly chenh lech).';
comment on column public.kiem_kho_chenh_lech_xu_ly.dot_kiem_kho is 'Dot kiem kho — khop cot dot_kiem_kho cua public.kiem_kho.';
comment on column public.kiem_kho_chenh_lech_xu_ly.ma_sp is 'Ma san pham nguyen ban, giu day du hau to lo/serial neu co.';
comment on column public.kiem_kho_chenh_lech_xu_ly.loai_phieu is 'nhap hoac xuat — loai phieu dieu chinh da tao.';
comment on column public.kiem_kho_chenh_lech_xu_ly.so_luong_dieu_chinh is 'So luong da dieu chinh (tri tuyet doi cua chenh lech tai thoi diem xu ly).';
comment on column public.kiem_kho_chenh_lech_xu_ly.ma_phieu_dieu_chinh is 'Ma phieu tao o public.phieu_xuat_nhap_kho (DB chinh).';
comment on column public.kiem_kho_chenh_lech_xu_ly.nguoi_xu_ly is 'Nguoi bam tao phieu dieu chinh.';
comment on column public.kiem_kho_chenh_lech_xu_ly.xu_ly_luc is 'Thoi diem tao phieu dieu chinh.';
