-- Bảng kiểm kho — DB phiếu cân (njdlkyxdieefeebcyaov)
-- Chạy an toàn trong Supabase SQL Editor:
-- https://supabase.com/dashboard/project/njdlkyxdieefeebcyaov/sql/new

create table if not exists public.kiem_kho (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  ten_kho text,
  dot_kiem_kho text,
  ma_nvl text,
  ma_sp text,
  ten_sp text,
  loai_sp text,
  ngay_gio_kiem_kho timestamptz not null default now(),
  nguoi_kiem_kho text,
  da_dong_bo boolean not null default false,
  dong_bo_luc timestamptz
);

alter table public.kiem_kho
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists ten_kho text,
  add column if not exists dot_kiem_kho text,
  add column if not exists ma_nvl text,
  add column if not exists ma_sp text,
  add column if not exists ten_sp text,
  add column if not exists loai_sp text,
  add column if not exists ngay_gio_kiem_kho timestamptz not null default now(),
  add column if not exists nguoi_kiem_kho text,
  add column if not exists da_dong_bo boolean not null default false,
  add column if not exists dong_bo_luc timestamptz;

create index if not exists kiem_kho_ngay_gio_idx on public.kiem_kho (ngay_gio_kiem_kho desc);
create index if not exists kiem_kho_ma_sp_idx on public.kiem_kho (ma_sp);
create index if not exists kiem_kho_ma_nvl_idx on public.kiem_kho (ma_nvl);
create index if not exists kiem_kho_ten_kho_idx on public.kiem_kho (ten_kho);
create index if not exists kiem_kho_dot_kiem_kho_idx on public.kiem_kho (dot_kiem_kho);
create index if not exists kiem_kho_da_dong_bo_idx on public.kiem_kho (da_dong_bo, id);

alter table public.kiem_kho enable row level security;

drop policy if exists "kiem_kho_select_all" on public.kiem_kho;
create policy "kiem_kho_select_all"
  on public.kiem_kho for select
  using (true);

drop policy if exists "kiem_kho_insert_all" on public.kiem_kho;
create policy "kiem_kho_insert_all"
  on public.kiem_kho for insert
  with check (true);

drop policy if exists "kiem_kho_update_all" on public.kiem_kho;
create policy "kiem_kho_update_all"
  on public.kiem_kho for update
  using (true)
  with check (true);

drop policy if exists "kiem_kho_delete_all" on public.kiem_kho;
create policy "kiem_kho_delete_all"
  on public.kiem_kho for delete
  using (true);

grant select, insert, update, delete on table public.kiem_kho to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

comment on table public.kiem_kho is 'Phieu / dong kiem kho.';
comment on column public.kiem_kho.ten_kho is 'Ten kho.';
comment on column public.kiem_kho.dot_kiem_kho is 'Dot kiem kho — phan biet cac lan kiem.';
comment on column public.kiem_kho.ma_nvl is 'Ma NVL = tien to truoc dau _ cua ma quet.';
comment on column public.kiem_kho.ma_sp is 'Ma quet day du (tien to + hau to).';
comment on column public.kiem_kho.ten_sp is 'Ten san pham.';
comment on column public.kiem_kho.loai_sp is 'Loai san pham.';
comment on column public.kiem_kho.ngay_gio_kiem_kho is 'Thoi diem kiem kho.';
comment on column public.kiem_kho.nguoi_kiem_kho is 'Nguoi thuc hien kiem kho.';
comment on column public.kiem_kho.da_dong_bo is 'Da cong dong kiem kho nay vao san_pham.ton_dau_ky.';
comment on column public.kiem_kho.dong_bo_luc is 'Thoi diem dong bo vao ton dau.';
