-- Chay toan bo file nay trong Supabase SQL Editor (Project > SQL > New query)
-- An toan khi chay lai nhieu lan (add column if not exists)

create table if not exists public.cai_dat_thoi_gian (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

alter table public.cai_dat_thoi_gian
  add column if not exists hang_muc text,
  add column if not exists loai_cai_dat text,
  add column if not exists khung_gio text,
  add column if not exists ma_cai_dat text,
  add column if not exists ten_cai_dat text,
  add column if not exists gio_bat_dau time,
  add column if not exists gio_ket_thuc time,
  add column if not exists gia_tri text,
  add column if not exists nhom text default 'Chung',
  add column if not exists ghi_chu text;

alter table public.cai_dat_thoi_gian enable row level security;

drop policy if exists "cai_dat_thoi_gian_select_all" on public.cai_dat_thoi_gian;
create policy "cai_dat_thoi_gian_select_all"
  on public.cai_dat_thoi_gian for select
  using (true);

drop policy if exists "cai_dat_thoi_gian_insert_all" on public.cai_dat_thoi_gian;
create policy "cai_dat_thoi_gian_insert_all"
  on public.cai_dat_thoi_gian for insert
  with check (true);

drop policy if exists "cai_dat_thoi_gian_update_all" on public.cai_dat_thoi_gian;
create policy "cai_dat_thoi_gian_update_all"
  on public.cai_dat_thoi_gian for update
  using (true)
  with check (true);

drop policy if exists "cai_dat_thoi_gian_delete_all" on public.cai_dat_thoi_gian;
create policy "cai_dat_thoi_gian_delete_all"
  on public.cai_dat_thoi_gian for delete
  using (true);

comment on table public.cai_dat_thoi_gian is 'Cau hinh thoi gian he thong.';
comment on column public.cai_dat_thoi_gian.hang_muc is 'Ten hang muc cai dat.';
comment on column public.cai_dat_thoi_gian.loai_cai_dat is 'Loai/nhom cai dat.';
comment on column public.cai_dat_thoi_gian.khung_gio is 'Khung gio hien thi, VD: 08:00 - 17:00.';
comment on column public.cai_dat_thoi_gian.gio_bat_dau is 'Gio bat dau.';
comment on column public.cai_dat_thoi_gian.gio_ket_thuc is 'Gio ket thuc.';
