-- Chạy lại an toàn trong Supabase SQL Editor.
-- Phiếu thu tiền khách hàng (ghi nhận trong trang Quản lý xe & lái xe).

create table if not exists public.thu_tien_khach_hang (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

alter table public.thu_tien_khach_hang
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists ngay_thu timestamptz not null default now(),
  add column if not exists ma_khach_hang text,
  add column if not exists ten_khach_hang text not null,
  add column if not exists so_tien numeric(18,2) not null default 0,
  add column if not exists hinh_thuc text not null default 'Tiền mặt',
  add column if not exists xe_id bigint,
  add column if not exists bien_so_xe text,
  add column if not exists ma_nhan_su text,
  add column if not exists nguoi_thu text,
  add column if not exists ghi_chu text,
  add column if not exists anh_url text,
  add column if not exists anh_public_id text;

create index if not exists thu_tien_khach_hang_ngay_thu_idx
  on public.thu_tien_khach_hang (ngay_thu desc);
create index if not exists thu_tien_khach_hang_khach_hang_idx
  on public.thu_tien_khach_hang (ma_khach_hang);

alter table public.thu_tien_khach_hang enable row level security;

drop policy if exists "thu_tien_khach_hang_select_all" on public.thu_tien_khach_hang;
create policy "thu_tien_khach_hang_select_all" on public.thu_tien_khach_hang for select using (true);
drop policy if exists "thu_tien_khach_hang_insert_all" on public.thu_tien_khach_hang;
create policy "thu_tien_khach_hang_insert_all" on public.thu_tien_khach_hang for insert with check (true);
drop policy if exists "thu_tien_khach_hang_update_all" on public.thu_tien_khach_hang;
create policy "thu_tien_khach_hang_update_all" on public.thu_tien_khach_hang for update using (true) with check (true);
drop policy if exists "thu_tien_khach_hang_delete_all" on public.thu_tien_khach_hang;
create policy "thu_tien_khach_hang_delete_all" on public.thu_tien_khach_hang for delete using (true);

comment on table public.thu_tien_khach_hang is 'Phieu thu tien khach hang, dong bo giam cong no trong bang khach_hang.';
